### ISSUE TITLE
Request for a 0.0.13 release

### ISSUE THREAD

**Issue by Trott** [observing/devnull#5]
Hi! Thanks for the great module! I was wondering if there's any chance of lobbying for a 0.0.13 release so we can `npm install` a version that doesn't trigger the deprecation warning about `process.eventEmitter`?

**Comment by Trott** [comment]
Now testing with the Node.js v7 beta and 0.0.12 fails entirely. Works with current master, though. Please publish 0.0.13? Pretty please?

**Comment by Trott** [comment]
Node.js v7 is out and the currently-published version of this package does not work with it. The master branch should be fine. Any chance you can do a `npm version patch && npm publish`?

**Comment by Trott** [comment]
While we're waiting for a new version to hopefully be published soon, one possible workaround (that would hopefully be temporary only):

``` console
npm install --save devnull@https://github.com/observing/devnull.git#ff99281602feca0cf3bdf0e6d36fedbf1b566523
```

**Comment by nwhitmont** [comment]
any update on this?

**Comment by dancyfits** [comment]
@3rd-Eden @Swaagie 
Master branch ``` npm publish ```

@everyoneelse
Until this is updated on npmjs
``` npm install devnull13 ```
or use the command @trott posted above

Although if your project depends on it, it might be a better idea to pull the latest commits from this repo or change 

``` var EventEmitter = process.EventEmitter; ```
to
``` var EventEmitter = require('events'); ```

in ``` node_modules/devnull/transports/transport.js```
Just in case this repo does get updated on npm, this way you won't have to worry about changing dependencies
